### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir './bin'

### ISSUE THREAD

**Issue by Prefix** [BeepIsla/csgo-broadcast#2]
Error: ENOENT: no such file or directory, scandir './bin'
    at Object.readdirSync (fs.js:785:3)
    at server.get (/home/discord/Broadcast/private/api.js:11:20)
    at Layer.handle [as handle_request] (/home/discord/Broadcast/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/discord/Broadcast/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/discord/Broadcast/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/discord/Broadcast/node_modules/express/lib/router/layer.js:95:5)
    at /home/discord/Broadcast/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/discord/Broadcast/node_modules/express/lib/router/index.js:335:12)
    at next (/home/discord/Broadcast/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/home/discord/Broadcast/node_modules/express/lib/middleware/init.js:40:5)

**Comment by BeepIsla** [comment]
Create a directory called `bin`

EDIT: Just now made this commit https://github.com/BeepFelix/csgo-broadcast/commit/1413752f8f7ad0dda42ab956f22321184bf7a9d9 which added the folder which was suppose to be in there the entire time but got swallowed.
